### ISSUE TITLE
Haw to get version in code after build in VSTS

### ISSUE THREAD

**Issue by boubaker-chieb** [MrTarantula/ProjectVersionTools#3]
I'm was looking  for a tool to set auto-increment the version  of my app after evry TFS Build untel i found this tool, it seem that it can respond to my needs, but i did'nt understand how to use it, i added the task to my job, i added olso the specified variables.  buid is succeeded.
is there any way to get version in code after build in VSTS ?

**Comment by MrTarantula** [comment]
This extension only mutates the csproj/vbproj file at build time, on the build agent machine. It cannot commit any changes back to the codebase. What I have used it for is incrementing the revision number using the [build ID variable](https://docs.microsoft.com/en-us/vsts/build-release/concepts/definitions/build/options). You don't have control over the number, but it increments at each build.

**Comment by MrTarantula** [comment]
This is not possible with my extension. Closing.
