### ISSUE TITLE
Incorrect property used for newer csproj format files?

### ISSUE THREAD

**Issue by conficient** [MrTarantula/ProjectVersionTools#4]
I was looking at using the *Get Application Version As Variables* for a .NET Standard library - it failed with the following error.
```
2018-05-15T09:49:20.9696850Z ##[error]Cannot read property 'textContent' of undefined
2018-05-15T09:49:20.9696850Z ##[section]Finishing: Get Application Version as variables from Anvil.Dates/Anvil.Dates.csproj
```
Looking at the code, it expects to see an `<ApplicationVersion>` tag. The version of a package in the new `csproj` file format is `<Version>` (as seen in the project settings dialog). Did you plan to support the newer format? It might be worth amending to search for different version values? 

Or is 'ApplicationVersion' your own setting which you push into the project?

**Comment by MrTarantula** [comment]
You're correct. I wrote this for transforming old vbproj files of projects I inherited. I either need to add a disclaimer or update the extension. I will also accept a PR if you want to give it a shot.

**Comment by conficient** [comment]
I've actually created my own extension to fit my purposes, but thanks
